/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeViews;

import AdminPannel.AdminPage;
import EmployeeViews.Add;
import EmployeeViews.ToParts;
import UniversalHandler.DerbyConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexmasse
 */
public class CarSold extends javax.swing.JFrame {
    /**
     * Creates new form Update
     */
    public CarSold() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        searchFieldS = new javax.swing.JTextField();
        DropDown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        admin = new javax.swing.JMenuItem();
        add = new javax.swing.JMenu();
        addCar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        SearchMenu = new javax.swing.JMenuItem();
        SoldMenu = new javax.swing.JMenu();
        SCL = new javax.swing.JMenuItem();
        PartsMenu = new javax.swing.JMenuItem();
        AP = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "VIN", "Make", "Model", "Year", "Price(Listed)", "Price(Sold)", "Engine", "Trans", "Bought By", "Sold By", "CustomerID"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        searchFieldS.setText("*");
        searchFieldS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldSActionPerformed(evt);
            }
        });

        DropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIN", "Make", "Model", "CustomerID" }));

        jLabel1.setText("Search For: ");

        jLabel2.setText("By");

        jLabel3.setText("Sold Car List");

        jMenu7.setText("File");

        login.setText("Log in");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jMenu7.add(login);

        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu7.add(logout);

        admin.setText("Admin Panel");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jMenu7.add(admin);

        jMenuBar3.add(jMenu7);

        add.setText("Edit");

        addCar.setText("Add Car");
        addCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarActionPerformed(evt);
            }
        });
        add.add(addCar);

        jMenuBar3.add(add);

        jMenu5.setText("View");

        SearchMenu.setText("Search (main)");
        SearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMenuActionPerformed(evt);
            }
        });
        jMenu5.add(SearchMenu);

        SoldMenu.setText("Lists");

        SCL.setText("Sold Cars List");
        SCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCLActionPerformed(evt);
            }
        });
        SoldMenu.add(SCL);

        PartsMenu.setText("Car Parts List");
        PartsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartsMenuActionPerformed(evt);
            }
        });
        SoldMenu.add(PartsMenu);

        jMenu5.add(SoldMenu);

        jMenuBar3.add(jMenu5);

        AP.setText("Other");

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        AP.add(about);

        jMenuBar3.add(AP);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchFieldS, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(DropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(DropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchFieldS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            listCar();
        } catch (SQLException ex) {
            Logger.getLogger(CarSold.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchFieldSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldSActionPerformed
         jButton1ActionPerformed(evt);
    }//GEN-LAST:event_searchFieldSActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        AdminPage ap=new AdminPage();
        String AdminUserSupplied=JOptionPane.showInputDialog("Enter Administrator Username:");
        String AdminPassSupplied=JOptionPane.showInputDialog("Enter Administrator Password:");
        if(AdminUserSupplied.equalsIgnoreCase("root") && AdminPassSupplied.equalsIgnoreCase("toor"))
        {
            ap.AdminMain();
        }
    }//GEN-LAST:event_adminActionPerformed

    private void addCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarActionPerformed
        Add.add();
    }//GEN-LAST:event_addCarActionPerformed

    private void SearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMenuActionPerformed
        String v=(String) Table.getValueAt(Table.getSelectedRow(),0);
        searchFieldS.setText(v);
    }//GEN-LAST:event_SearchMenuActionPerformed

    private void SCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCLActionPerformed
        CarSold cs = new CarSold();
        try {
            CarSold.carSold();
        } catch (SQLException ex) {
            System.out.println("Error:"+ ex);
        }
    }//GEN-LAST:event_SCLActionPerformed

    private void PartsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartsMenuActionPerformed
        ToParts pt=new ToParts();
        pt.toParts();
    }//GEN-LAST:event_PartsMenuActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // figure out how to do a popup for the about jpanel...
    }//GEN-LAST:event_aboutActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableMouseClicked

    public static void carSold() throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarSold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarSold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarSold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarSold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        System.out.println("CarSold Class Called!");
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarSold().setVisible(true);
            }
        });
    }
private DefaultTableModel listCar() throws SQLException
    {
        String selectedCat= String.valueOf(DropDown.getSelectedItem());
        String sql;
        if(searchFieldS.getText().equals("*"))
        {
            sql="SELECT * FROM SOLDCARS";
        }
        else
        {
            sql="SELECT * FROM SOLDCARS WHERE "+selectedCat+"='"+searchFieldS.getText()+"'";
        }
        DerbyConnect db=new DerbyConnect();
        Statement stmt=db.st();
        DefaultTableModel model=(DefaultTableModel)Table.getModel();
        model.setRowCount(0);
        String[] loadCar=new String[11]; 
        try{
            ResultSet rs=stmt.executeQuery(sql);
            while (rs.next())//have to make it so that it only keeps the number one time.
            {
                for(int i=0;i<loadCar.length;i++)
                {
                    loadCar[i]=rs.getString(i+1);
                    
                }
                model.addRow(new Object[]{loadCar[0],loadCar[1],loadCar[2],loadCar[3],loadCar[4],loadCar[5],loadCar[6],loadCar[7],loadCar[8],loadCar[9],loadCar[10]});
            }
            rs.close();
        }
        catch(SQLException ex)
        {
           System.out.println("SQLException(ListAll): " + ex.getMessage());
        }
        stmt.close();
        return model;
    }
   
    public static void closeSold()
    {
        System.exit(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AP;
    private javax.swing.JComboBox<String> DropDown;
    private javax.swing.JMenuItem PartsMenu;
    private javax.swing.JMenuItem SCL;
    private javax.swing.JMenuItem SearchMenu;
    private javax.swing.JMenu SoldMenu;
    private javax.swing.JTable Table;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenu add;
    private javax.swing.JMenuItem addCar;
    private javax.swing.JMenuItem admin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem login;
    private javax.swing.JMenuItem logout;
    private javax.swing.JTextField searchFieldS;
    // End of variables declaration//GEN-END:variables
}
