/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeViews;

import AdminPannel.AdminPage;
import EmployeeControllers.CarToParts;
import UniversalHandler.DerbyConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexmasse
 */
public class ToParts extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public ToParts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchFieldP = new javax.swing.JTextField();
        DropDown = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sol = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        admin = new javax.swing.JMenuItem();
        add = new javax.swing.JMenu();
        addCar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        SearchMeun = new javax.swing.JMenuItem();
        PartsMenu = new javax.swing.JMenu();
        SoldMenu = new javax.swing.JMenuItem();
        CPL = new javax.swing.JMenuItem();
        AP = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Make", "Model", "Year", "Engine", "Trans", "Price", "Number"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Search for");

        searchFieldP.setText("*");
        searchFieldP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldPActionPerformed(evt);
            }
        });

        DropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make", "Model", "Engine", "Transmission" }));

        jLabel2.setText("By");

        jLabel3.setText("Car Parts List");

        sol.setText("SOLD");
        sol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solActionPerformed(evt);
            }
        });

        jMenu7.setText("File");

        jMenuItem6.setText("Log in");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuItem4.setText("Log out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        admin.setText("Admin Panel");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jMenu7.add(admin);

        jMenuBar3.add(jMenu7);

        add.setText("Edit");

        addCar.setText("Add Car");
        addCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarActionPerformed(evt);
            }
        });
        add.add(addCar);

        jMenuBar3.add(add);

        jMenu5.setText("View");

        SearchMeun.setText("Search (main)");
        SearchMeun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMeunActionPerformed(evt);
            }
        });
        jMenu5.add(SearchMeun);

        PartsMenu.setText("Lists");

        SoldMenu.setText("Sold Cars List");
        SoldMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldMenuActionPerformed(evt);
            }
        });
        PartsMenu.add(SoldMenu);

        CPL.setText("Car Parts List");
        CPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPLActionPerformed(evt);
            }
        });
        PartsMenu.add(CPL);

        jMenu5.add(PartsMenu);

        jMenuBar3.add(jMenu5);

        AP.setText("Other");

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        AP.add(about);

        jMenuBar3.add(AP);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchFieldP, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(sol))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(searchFieldP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(sol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            listParts();
        } catch (SQLException ex) {
           System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        AdminPage ap=new AdminPage();
        String AdminUserSupplied=JOptionPane.showInputDialog("Enter Administrator Username:");
        String AdminPassSupplied=JOptionPane.showInputDialog("Enter Administrator Password:");
        if(AdminUserSupplied.equalsIgnoreCase("root") && AdminPassSupplied.equalsIgnoreCase("toor"))
        {
            ap.AdminMain();
        }
    }//GEN-LAST:event_adminActionPerformed

    private void addCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarActionPerformed
        Add.add();
    }//GEN-LAST:event_addCarActionPerformed

    private void SearchMeunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMeunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMeunActionPerformed

    private void SoldMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldMenuActionPerformed

    }//GEN-LAST:event_SoldMenuActionPerformed

    private void CPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPLActionPerformed
        ToParts pt=new ToParts();
        pt.toParts();
    }//GEN-LAST:event_CPLActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // figure out how to do a popup for the about jpanel...
    }//GEN-LAST:event_aboutActionPerformed

    private void solActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solActionPerformed
        String id=searchFieldP.getText();
        CarToParts cp=new CarToParts();
        try {
            cp.delParts(id);
        } catch (SQLException ex) {
           System.out.println(ex);
        }
    }//GEN-LAST:event_solActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        String v=(String) Table.getValueAt(Table.getSelectedRow(),6);
        searchFieldP.setText(v);
    }//GEN-LAST:event_TableMouseClicked

    private void searchFieldPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldPActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_searchFieldPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void toParts() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        System.out.println("ToParts Class Called!");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToParts().setVisible(true);
            }
        });
        
    }

    private void listParts() throws SQLException
    {
        DerbyConnect db=new DerbyConnect();
        Statement stmt=db.st();
        String selectedCat= String.valueOf(DropDown.getSelectedItem());
        String sql;
        if(searchFieldP.getText().equals("*"))
        {
             sql="SELECT * FROM PARTS";
        }
        else
        {
             sql="SELECT * FROM PARTS WHERE "+selectedCat+"='"+searchFieldP.getText()+"'";
        }
        DefaultTableModel model=(DefaultTableModel)Table.getModel();
        model.setRowCount(0);
        String[] loadCar=new String[7];
        try{
            ResultSet rs=stmt.executeQuery(sql);
            while (rs.next())//have to make it so that it only keeps the number one time.
            {
                for(int i=0;i<loadCar.length;i++)
                {
                    loadCar[i]=rs.getString(i+1);
                }
                model.addRow(new Object[]{loadCar[0],loadCar[1],loadCar[2],loadCar[3],loadCar[4],loadCar[5], loadCar[6]});
            }
        }
        catch(SQLException ex)
        {
           System.out.println("SQLException(ListAll): " + ex.getMessage());
        }
        stmt.close();
    }
    public static void closePart()
    {
        System.exit(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AP;
    private javax.swing.JMenuItem CPL;
    private javax.swing.JComboBox<String> DropDown;
    private javax.swing.JMenu PartsMenu;
    private javax.swing.JMenuItem SearchMeun;
    private javax.swing.JMenuItem SoldMenu;
    private javax.swing.JTable Table;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenu add;
    private javax.swing.JMenuItem addCar;
    private javax.swing.JMenuItem admin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchFieldP;
    private javax.swing.JButton sol;
    // End of variables declaration//GEN-END:variables
}
